### ISSUE TITLE
pymunk broken by new pycparser version (2.18)‏

### ISSUE THREAD

**Issue by gevak** [viblo/pymunk#118]
I've made a fresh install of pymunk today and noticed that it fails to run my project.
It gives errors on calls to CFFI, for example:
 
>cffi.error.CDefError: cannot parse "typedef void (*cpSpaceDebugDrawCircleImpl)(cpVect pos, cpFloat angle, cpFloat radius, cpSpaceDebugColor outlineColor, cpSpaceDebugColor fillColor, cpDataPointer data)"
:87:16: before: cpSpaceDebugDrawCircleImpl

I got the same error when taking an already working setup of pymunk and updating pycparser with pip:
>pip install pycparser --upgrade

and the errors disappeared when I downgraded pycparser:
>pip install pycparser==2.17

Long story short, I looked into it and I think I know the cause of the issue and how it can be solved.
<h2>The cause of the issue</h2>
A new release of the package pycparser, used by CFFI, was published a week~ ago. 
One difference between the new version 2.18 and the previous one is that it now fails to parse source code that includes redefinitions. I don't know why this behaviour was changed and whether it was intentional, but it seems to me that a change in PLY (Python Lex-Yacc) was the trigger. 

These redefinitions did work in version 2.17, and they are relied on by pymunk:
Every function pointer type is defined in the _chipmunk_cffi_abi.py file.
Afterwards, those functions are redefined when pymunk makes calls to the ffi.callback decorator.
The generated source code that is sent to pycparser contains two definitions of the function type, for instance:
>source = """
typedef int cpBodyVelocityFunc;
void __dummy(
typedef void (*cpBodyVelocityFunc)(cpBody body,...)
);
"""

which causes an error on pycparser 2.18 due to the redefinition of cpBodyVelocityFunc.

<h2>Possible solutions</h2>
Assuming the change in pycparser / PLY was intentional and is here to stay,
I think any one of these changes should fix the issue within pymunk:  

1. Passing the function types by name instead of redefining them in calls to ffi.callback().  For instance:
>@ffi.callback("typedef void (*cpBodyVelocityFunc)"
            "(cpBody *body, cpVect gravity, cpFloat damping, cpFloat dt)")

Can simply be replaced with:
> @ffi.callback("cpBodyVelocityFunc")

2. The type of the function can be redefined when calling ffi.callback(), but without being named or with a different name.  For instance:
 >@ffi.callback("typedef void (*cpBodyVelocityFunc)"
            "(cpBody *body, cpVect gravity, cpFloat damping, cpFloat dt)")

Can be replaced with:
>@ffi.callback("void (*) (cpBody *body, cpVect gravity, cpFloat damping, cpFloat dt)")

Or with:
 >@ffi.callback("typedef void (*cpBodyVelocityFunc2)"
            "(cpBody *body, cpVect gravity, cpFloat damping, cpFloat dt)")

Hopefully this will help you solve the issue.

**Comment by viblo** [comment]
Thanks again for the report. I have made a new release of Pymunk with your proposed solution 1. Thanks! Feel free to try it out.

**Comment by gevak** [comment]
I tested it and I can confirm that pymunk 5.3.1 works perfectly with the new pycparser 2.18 on my machine.
Thanks for the quick fix.
